apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-worker
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-worker
  template:
    metadata:
      labels:
        app: secure-worker
    spec:
      serviceAccountName: worker-sa
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 2000
      containers:
      - name: worker
        image: worker:v1
        imagePullPolicy: Never
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
        envFrom:
        - configMapRef:
            name: worker-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"
